version: '3.8'

services:
  backend:
    image: grupo1backend:1
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - grupo1back_net
  db1:
    image: postgres:15.0-bullseye
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_DB=grupo1db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_grupo1vol_data:/var/lib/postgresql/data/pgdata
    networks:
      - grupo1back_net
           
volumes:
  pg_grupo1vol_data:
    external: true

networks:
  grupo1back_net:
    external: true

secrets:
  db_dev_pass:
    external: true  